version: "3"
services:
  reactive-mongodb:
    image: mongo:latest
    container_name: "reactive-mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: smart-city
    ports:
      - 8080:8080
    links:
      - reactive-mongodb