version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
#    command: --smallfiles
  permissions:
    image: permissions:1.0
    container_name: "permissions"
    ports:
      - 8082:8082
    links:
      - mongodb
  smart-city:
    image: smart-city:1.0
    container_name: "smart-city"
    ports:
      - 8081:8081
    links:
      - mongodb